file_tree_ops = [
    "getdents, mkdir",
    "getdents, rmdir",
    "getdents, rename",
    "getdents, open",
    "getdents, close",
    "getdents, dup",
    "getdents, dup2",
    "getdents, link",
    "getdents, symlink",
    "getdents, unlink",
    "getdents, chmod",
    "getdents, fchmod",

    "mkdir, rmdir",
    "mkdir, rename",
    "mkdir, open",
    "mkdir, symlink",
    "mkdir, setxattr",
    "mkdir, removexattr",
    "mkdir, listxattr",
    "mkdir, getxattr",
    "mkdir, chmod",
    "mkdir, fchmod",
    "mkdir, stat",
    "mkdir, lstat",
    "mkdir, fstat",
    "mkdir, fsync",
    "mkdir, sync",

    "open, open",

    "open, close",
    "open, dup",
    "open, dup2",
    "open, link",
    "open, symlink",
    "open, unlink",
    "open, fsetxattr",
    "open, fremovexattr",
    "open, flistxattr",
    "open, fgetxattr",
    "open, ftruncate",
    "open, fchmod",
    "open, fstat",
    "open, fsync",
    "open, fdatasync"

    "close, dup",
    "close, dup2"
    "close, fsetxattr",
    "close, fremovexattr",
    "close, flistxattr",
    "close, fgetxattr",
    "close, ftruncate",
    "close, fchmod",
    "close, fstat",
    "close, fsync",
    "close, fdatasync"

    "link, symlink",
    "link, unlink",
    "link, setxattr",
    "link, removexattr",
    "link, listxattr",
    "link, getxattr",
    "link, lremovexattr",
    "link, llistxattr",
    "link, lgetxattr",
    "link, truncate",
    "link, chmod",
    "link, stat",
    "link, lstat",
    "link, sync",
    "link, fsync",

    "symlink, unlink",
    "symlink, readlink",
    "symlink, setxattr",
    "symlink, removexattr",
    "symlink, listxattr",
    "symlink, getxattr",
    "symlink, lremovexattr",
    "symlink, llistxattr",
    "symlink, lgetxattr",
    "symlink, truncate",
    "symlink, chmod",
    "symlink, stat",
    "symlink, lstat",
    "symlink, sync",
    "symlink, fsync",

    "unlink, readlink",
    "unlink, setxattr",
    "unlink, removexattr",
    "unlink, listxattr",
    "unlink, getxattr",
    "unlink, lremovexattr",
    "unlink, llistxattr",
    "unlink, lgetxattr",
    "unlink, truncate",
    "unlink, chmod",
    "unlink, stat",
    "unlink, lstat",
    "unlink, sync",
    "unlink, fsync"
]


regular_ops = [
    "setxattr, setxattr",
    "setxattr, lsetxattr",
    "setxattr, listxattr",
    "setxattr, llistxattr",
    "setxattr, removexattr",
    "setxattr, lremovexattr",
    "setxattr, getxattr",
    "setxattr, lgetxattr",
    "setxattr, chmod",
    "setxattr, sync",

    "setxattr, fsetxattr",
    "setxattr, flistxattr",
    "setxattr, fremovexattr",
    "setxattr, fgetxattr",
    "setxattr, fchmod",
    "setxattr, fsync",


    "lsetxattr, lsetxattr",
    "lsetxattr, llistxattr",
    "lsetxattr, lremovexattr",
    "lsetxattr, lgetxattr",
    "lsetxattr, fsetxattr",
    "lsetxattr, flistxattr",
    "lsetxattr, fremovexattr",
    "lsetxattr, fgetxattr",
    "lsetxattr, fsync",
    "lsetxattr, sync",

    "listxattr, removexattr",
    "listxattr, chmod",
    "listxattr, fchmod",
    "listxattr, fsetxattr",
    "listxattr, fremovexattr",

    "llistxattr, lremovexattr",
    "llistxattr, chmod",
    "llistxattr, fchmod",
    "llistxattr, fsetxattr",
    "llistxattr, fremovexattr",

    "getxattr, removexattr",
    "getxattr, chmod",
    "getxattr, fchmod",
    "getxattr, fsetxattr",
    "getxattr, fremovexattr",

    "lgetxattr, lremovexattr",
    "lgetxattr, chmod",
    "lgetxattr, fchmod",
    "lgetxattr, fsetxattr",
    "lgetxattr, fremovexattr",

    "removexattr, removexattr",
    "removexattr, chmod",
    "removexattr, fchmod",
    "removexattr, fsetxattr",
    "removexattr, flistxattr",
    "removexattr, fremovexattr",
    "removexattr, fgetxattr",
    "removexattr, fsync",
    "removexattr, sync",

    "lremovexattr, lremovexattr",
    "lremovexattr, chmod",
    "lremovexattr, fchmod",
    "lremovexattr, fsetxattr",
    "lremovexattr, flistxattr",
    "lremovexattr, fremovexattr",
    "lremovexattr, fgetxattr",
    "lremovexattr, fsync",
    "lremovexattr, sync",

    "fsetxattr, chmod",
    "fsetxattr, fchmod",
    "fsetxattr, fsync",
    "fsetxattr, sync",

    "flistxattr, chmod",
    "flistxattr, fchmod",

    "fremovexattr, fchmod",
    "fremovexattr, chmod",
    "fremovexattr, fsync",
    "fremovexattr, sync",

    "fgetxattr, fchmod",
    "fgetxattr, chmod",

    "truncate, truncate",
    "truncate, ftruncate",
    "truncate, write",
    "truncate, pwrite64",
    "truncate, lseek",
    "truncate, read",
    "truncate, pread64",
    "truncate, chmod",
    "truncate, fchmod",
    "truncate, stat",
    "truncate, lstat",
    "truncate, fstat",
    "truncate, fsync",
    "truncate, sync",
    "truncate, fdatasync",

    "ftruncate, ftruncate",
    "ftruncate, write",
    "ftruncate, pwrite64",
    "ftruncate, lseek",
    "ftruncate, read",
    "ftruncate, pread64",
    "ftruncate, chmod",
    "ftruncate, fchmod",
    "ftruncate, stat",
    "ftruncate, lstat",
    "ftruncate, fstat",
    "ftruncate, fsync",
    "ftruncate, sync",
    "ftruncate, fdatasync",

    "write, write",
    "write, pwrite64",
    "write, lseek",
    "write, read",
    "write, pread64",
    "write, stat",
    "write, lstat",
    "write, fstat",
    "write, fsync",
    "write, sync",

    "pwrite64, pwrite64",
    "pwrite64, lseek",
    "pwrite64, read",
    "pwrite64, pread64",
    "pwrite64, stat",
    "pwrite64, lstat",
    "pwrite64, fstat",
    "pwrite64, fsync",
    "pwrite64, sync",

    "lseek, lseek",
    "lseek, read",
    "lseek, pread64",

    "chmod, chmod",
    "chmod, fchmod",
    "fchmod, fchmod",
    "chmod, sync",
    "fchmod, sync",
    "chmod, stat",
    "chmod, fstat",
    "chmod, lstat",
    "fchmod, stat",
    "fchmod, fstat",
    "fchmod, lstat"
]